- name: Perform APT Upgrade on Online Hosts
  hosts: reachable_hosts
  gather_facts: false
  become: true
  ignore_unreachable: true

  tasks:

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
        force_apt_get: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: yes
        force_apt_get: true
        dpkg_options:
          - force-confold
          - force-confdef
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: true
        force_apt_get: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Clean APT cache
      ansible.builtin.apt:
        autoclean: true
        force_apt_get: true
      environment:
        DEBIAN_FRONTEND: noninteractive
