---
# Play 1: Identify all online hosts
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Check Connectivity
      ansible.builtin.wait_for_connection:
        timeout: 5
      ignore_unreachable: true
      register: conn_check
    - name: Group Reachable Hosts
      ansible.builtin.group.by:
        key: reachable_hosts
      when: conn_check is succeeded
      
# Play 2 Run All Tasks on reachable Hosts only
- hosts: reachable_hosts
  become: true
  tasks:
    - name: Execute on only online hosts
      ansible.builtin.debug:
        msg: "This host is online"
    - name: Update apt package cache
      apt:
        update_cache: yes
        dpkg_options: 'force-confold,force-confdef'
      register: apt_output

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        dpkg_options: 'force-confold,force-confdef'
      register: apt_output

    - name: Display upgrade results
      ansible.builtin.debug:
        var: apt_output.stdout_lines

    - name: Remove unused dependencies
      apt:
        autoremove: yes
